In [1]:
import numpy as np

In [18]:
a=[1,4,2]

In [19]:
b = [a, [7,41]]

In [24]:
c=a + [23,1]

In [25]:
c

[1, 4, 2, [45, 2], 23, 1]

In [22]:
b

[[1, 4, 2, [45, 2]], [7, 41]]

In [23]:
a

[1, 4, 2, [45, 2]]

In [27]:
a=np.array([1,3]).reshape(1,2)
b=np.array([5,2]).reshape(2,1)
np.dot(b,a)

array([[ 5, 15],
       [ 2,  6]])

In [28]:
a

array([[1, 3]])

In [5]:
np.arange(4,10,2)

array([4, 6, 8])

In [7]:
np.ones(6).reshape(2,3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
a=np.arange(10)

In [14]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
c=np.arange(1,4)
c

array([1, 2, 3])

In [21]:
c.reshape(3,1)

array([[1],
       [2],
       [3]])

In [22]:
c

array([1, 2, 3])